# Generated by Django 4.2.13 on 2024-05-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('lux', 'Lux'), ('family', 'Family')], max_length=10)),
                ('room_capacity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
