# Generated by Django 4.2.13 on 2024-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'verbose_name': 'Гостиничные номера', 'verbose_name_plural': 'Гостиничный номер'},
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='photo',
            field=models.ImageField(upload_to='room_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_capacity',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('lux', 'Lux'), ('family', 'Family')], max_length=10, verbose_name='Тип комнаты'),
        ),
        migrations.AlterModelTable(
            name='hotelroom',
            table='hotel_rooms',
        ),
    ]
