# Generated by Django 4.2.13 on 2024-05-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0002_alter_hotelroom_options_alter_hotelroom_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'verbose_name': 'Гостиничныt номера', 'verbose_name_plural': 'Гостиничныt номера'},
        ),
    ]
