# Generated by Django 4.2.13 on 2024-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_review_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='напишите отзыв'),
        ),
    ]
